//
// Created by itechbear on 9/10/15.
//

#include <iostream>
#include <boost/algorithm/string.hpp>

#include "lib/words_model.h"

int main(int argc, char *argv[]) {
  // vectors.bin is generated by word2vec.
  const std::string path = "/home/itechbear/Code/word2vec/vectors.bin";
  WordsModel model;
  if (!model.ParseFromFile(path)) {
    std::cerr << "Failed to parse file: " << path << std::endl;
    return -1;
  }

  ResultSet result_set(40);
  if (!model.GetNearestWords("this that", false, &result_set)) {
    std::cerr << "Failed to get nearest words. " << std::endl;
    return -1;
  }

  auto &queue = result_set.GetQueue();
  while (!queue.empty()) {
    std::cout << "distance: " << queue.top().GetDistance() << ", word: " << queue.top().GetToken() << std::endl;
    queue.pop();
  }

  return 0;
}
